name: image_manipulation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  flutter:
    sdk: flutter
  get: 4.6.1
  image: ^3.1.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+6
  numdart: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
